[ghosts.spirit]
name = "Spirit"
speed = 1.7
hunt_sanity = 50
evidence = ["EMF","SpiritBox","Writing"]
description = "Incense prevents hunt for 180s instead of 90"

[ghosts.wraith]
name = "Wraith"
speed = 1.7
hunt_sanity = 50
evidence = ["EMF","SpiritBox","DOTS"]
description = """
Will not ever step in salt.
Can randomly teleport to player, leaving EMF 2 or 5"""

[ghosts.phantom]
name = "Phantom"
speed = 1.7
hunt_sanity = 50
evidence = ["SpiritBox","Ultraviolet","DOTS"]
description = """
Will not appear in ghost photos
Less visible during hunts
"""

[ghosts.poltergeist]
name = "Poltergeist"
speed = 1.7
hunt_sanity = 50
evidence = ["SpiritBox", "Ultraviolet", "Writing"]
description = """
Can throw many items at once, -2% sanity for each item
Throws items more often during hunts
Higher change to throw objects"""

[ghosts.banshee]
name = "Banshee"
speed = 1.7
hunt_sanity = 50
evidence = ["Ultraviolet", "GhostOrbs", "DOTS"]
description = """
Unique scream through paramic (not guaranteed)
Will only go after its target during a hunt"""

[ghosts.jinn]
name = "Jinn"
min_speed = 1.7
max_speed = 2.5
hunt_sanity = 50
evidence = ["EMF", "Ultraviolet", "Freezing"]
description = """
Ability drops nearby players' sanity by 25% with EMF 2 at the breaker
Cannot turn off the fuse box
Faster when fuse box is on
"""

[ghosts.mare]
name = "Mare"
speed = 1.7
min_hunt_sanity = 40
max_hunt_sanity = 60
evidence = ["SpiritBox", "GhostOrbs", "Writing"]
description = """
Can turn off a light immediately after player turns it on
Cannot turn on lights (except TV or computer)
More likely to turn off/break lights
Hunts at 60% when lights off at ghost's position, 40% otherwise
"""

[ghosts.revenant]
name = "Revenant"
min_speed = 1.0
max_speed = 3.0
hunt_sanity = 50
evidence = ["GhostOrbs", "Writing", "Freezing"]
description = """
Fast once the player has been sensed (equipment, voice, line of sight)
"""

[ghosts.shade]
name = "Shade"
speed = 1.7
hunt_sanity = 35
evidence = ["EMF", "Writing", "Freezing"]
description = """
Extremely docile
Will not do interactions that emit EMF 2/3/5 if someone is in the room (writing excluded)
Cannot hunt if a player is in the room
More ghost events at lower sanity
More likely to appear as a shadow when manifesting (TODO: get % change)
Can appear as a shadow when spawned from music box or summoning circle
"""

[ghosts.demon]
name = "Demon"
speed = 1.7
min_hunt_sanity = 70
max_hunt_sanity = 100
evidence = ["Ultraviolet", "Writing", "Freezing"]
description = """
Incense only prevents hunts for 60s instead of 90s
20s minimum hunt cool down instead of 25s
Crucifix effective range increased by 50% (not displayed)
Can hunt at any sanity, standard hunts start at 70%
"""

[ghosts.yurei]
name = "Yurei"
speed = 1.7
hunt_sanity = 50
evidence = ["GhostOrbs", "Freezing", "DOTS"]
description = """
Can shut doors and drop nearby sanity 15% if a door is in the room
Can close an exit door outside of a hunt or ghost event
Incense locks it in the ghost room and blocks wandering for 60s
"""

[ghosts.oni]
name = "Oni"
speed = 1.7
hunt_sanity = 50
evidence = ["EMF", "Freezing", "DOTS"]
description = """
Drains 20% sanity on ghost events instead of 10%
Will never do airball event
More visible during hunts
More active when multiple people are around
"""

[ghosts.yokai]
name = "Yokai"
speed = 1.7
min_hunt_sanity = 50
max_hunt_sanity = 80
evidence = ["SpiritBox", "GhostOrbs", "DOTS"]
description = """
Short hearing range during hunts (try talking and see if it comes to you during a hunt)
More active when talked to
Hunts at 80% when talking nearby, 50% otherwise
"""

[ghosts.hantu]
name = "Hantu"
min_speed = 1.44
max_speed = 2.7
hunt_sanity = 50
evidence = ["Ultraviolet", "GhostOrbs", "Freezing"]
description = """
Ghost may have visible breath in any room during hunts with breaker off
Cannot turn on breaker
High chance to turn off breaker
Faster in colder temperatures, does not speed up in line-of-sight
Guaranteed freezing on nightmare/insanity
"""

[ghosts.goryo]
name = "Goryo"
speed = 1.7
hunt_sanity = 50
evidence = ["EMF", "Ultraviolet", "DOTS"]
description = """
DOTS only visible on screen in truck
DOTS rare when players are in the room
Can't change ghost room
Won't roam far
Guaranteed DOTS on nightmare/insanity
"""

[ghosts.myling]
name = "Myling"
speed = 1.7
hunt_sanity = 50
evidence = ["EMF", "Ultraviolet", "DOTS"]
description = """
Footsteps/vocal range shorter during hunts
More sounds through paramic
"""

[ghosts.onryo]
name = "Onryo"
speed = 1.7
hunt_sanity = 60
evidence = ["SpiritBox", "GhostOrbs", "Freezing"]
description = """
Will hunt at any sanity after extinguishing 3 firelights
Firelights act as crucifixes (4m range)
More player dead increases chance of extinguishing flame
"""

[ghosts.twins]
name = "The Twins"
min_speed = 1.53
max_speed = 1.87
hunt_sanity = 50
evidence = ["EMF", "SpiritBox", "Freezing"]
description = """
Twins often interact one after the other ('twinteraction')
Only one twin can emit EMF
Twinteraction may be visible on truck graph by changing slope during rising edge
Speed depends on which twin hunts
"""

[ghosts.raiju]
name = "Raiju"
min_speed = 1.7
max_speed = 2.5
min_hunt_sanity = 50
max_hunt_sanity = 65
evidence = ["EMF", "GhostOrbs", "DOTS"]
description = """
Longer electronics flicker range while hunting
Hunts at 65% near active player equipment
TODO: need to check if ground items count (e.g EMF reader)
Faster near player equipment
EMF 5 + Ghost Orbs on nightmare confirms
"""

[ghosts.obake]
name = "Obake"
speed = 1.7
hunt_sanity = 50
evidence = ["EMF", "Ultraviolet", "GhostOrbs"]
description = """
Chance for 6-finger handprints
Chance for 2-finger light switch prints
Flickers to a second model during hunts (guaranteed once per hunt)
Will not always leave UV
UV evidence can disappear sooner than two minutes
Guaranteed UV on nightmare/insanity
"""

[ghosts.mimic]
name = "The Mimic"
speed = 1.7
hunt_sanity = 50
evidence = ["SpiritBox", "Ultraviolet", "Freezing"]
description = """
Always shows ghost orbs, even though it does not count as an evidence
Copies behavior of other ghosts
Changes copied ghost every 30s - 2min
"""

[ghosts.moroi]
name = "Moroi"
min_speed = 1.5
max_speed = 3.71
hunt_sanity = 50
evidence = ["SpiritBox", "Writing", "Freezing"]
description = """
If heard through spirit box, player is cursed
Curse causes 2x sanity drain for the rest of the game
Blinded 50% longer when incensed 
Faster when average sanity is lower
Guaranteed spirit box on nightmare/insanity
"""


[ghosts.deogen]
name = "Deogen"
min_speed = 0.4
max_speed = 3.0
hunt_sanity = 40
evidence = ["SpiritBox", "Writing", "DOTS"]
description = """
Heavy breathing through spirit box if < 1m away
Will always find you during a hunt
Slows down considerably when close to the player
Increased chance for DOTS/Writing
"""

[ghosts.thaye]
name = "Thaye"
min_speed = 1.0
max_speed = 2.75
min_hunt_sanity = 15
max_hunt_sanity = 75
evidence = ["GhostOrbs", "Writing", "DOTS"]
description = """
Ages when near players (once every 1-2 min)
More active when younger
Higher chance for DOTS/Writing
Age determines hunt sanity (older = lower sanity)
Age determines speed (older = slower)
Will not speed up at line of sight
Writing + DOTS on nightmare confirms
"""